# Generated by Django 4.0.2 on 2022-03-20 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('token_address', models.CharField(max_length=200)),
                ('token_id', models.BigIntegerField()),
                ('user', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('quality', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Proto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('effect', models.TextField()),
                ('god', models.CharField(max_length=20)),
                ('set', models.CharField(max_length=20)),
                ('rarity', models.CharField(max_length=20)),
                ('mana', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=20)),
                ('tribe', models.CharField(max_length=20, null=True)),
                ('attack', models.IntegerField(null=True)),
                ('health', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(null=True)),
                ('cost', models.FloatField(null=True)),
                ('sell_id', models.CharField(max_length=200)),
                ('sell_type', models.CharField(max_length=20)),
                ('sell_token_address', models.CharField(max_length=200)),
                ('sell_token_id', models.BigIntegerField()),
                ('buy_type', models.CharField(max_length=20)),
                ('buy_token_address', models.CharField(max_length=200, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='proto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='main.proto'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('token_address', 'token_id')},
        ),
    ]
