# Generated by Django 4.0.2 on 2022-03-31 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('token_address', models.CharField(max_length=200)),
                ('token_id', models.BigIntegerField()),
                ('user', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('quality', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField(db_index=True)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Proto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('effect', models.CharField(max_length=500, null=True)),
                ('god', models.CharField(max_length=20)),
                ('set', models.CharField(max_length=20)),
                ('rarity', models.CharField(max_length=20)),
                ('mana', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=20)),
                ('tribe', models.CharField(max_length=20, null=True)),
                ('attack', models.IntegerField(null=True)),
                ('health', models.IntegerField(null=True)),
                ('qty_on_sale', models.IntegerField(null=True)),
                ('current_price', models.FloatField(null=True)),
                ('runner_price', models.FloatField(null=True)),
                ('ratio_price', models.FloatField(null=True)),
                ('stats_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(null=True)),
                ('cost', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=20)),
                ('usd', models.FloatField()),
                ('sell_id', models.CharField(max_length=200)),
                ('sell_type', models.CharField(max_length=20)),
                ('sell_token_address', models.CharField(max_length=200)),
                ('sell_token_id', models.BigIntegerField()),
                ('buy_type', models.CharField(max_length=20)),
                ('buy_token_address', models.CharField(max_length=200, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('scraped_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.asset')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='proto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='main.proto'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_price', models.FloatField()),
                ('prc7', models.FloatField()),
                ('prc14', models.FloatField()),
                ('prc30', models.FloatField()),
                ('prc60', models.FloatField()),
                ('vol7', models.IntegerField()),
                ('vol14', models.IntegerField()),
                ('vol30', models.IntegerField()),
                ('vol60', models.IntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='main.day')),
                ('proto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='main.proto')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('proto', 'day')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('token_address', 'token_id')},
        ),
    ]
