# Generated by Django 4.0.2 on 2022-04-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proto',
            name='ratio_price',
        ),
        migrations.AddField(
            model_name='proto',
            name='last_price',
            field=models.FloatField(null=True),
        ),
    ]
