# Generated by Django 4.0.2 on 2022-03-21 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_proto_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scraped_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
