# Generated by Django 4.0.2 on 2022-03-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_day_proto_last_stats_at_daystat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daystat',
            old_name='lowest_price',
            new_name='current_price',
        ),
        migrations.RemoveField(
            model_name='daystat',
            name='act_prc14',
        ),
        migrations.RemoveField(
            model_name='daystat',
            name='act_prc30',
        ),
        migrations.RemoveField(
            model_name='daystat',
            name='act_prc60',
        ),
        migrations.RemoveField(
            model_name='daystat',
            name='act_prc7',
        ),
        migrations.RemoveField(
            model_name='daystat',
            name='act_vol14',
        ),
        migrations.RemoveField(
            model_name='daystat',
            name='act_vol30',
        ),
        migrations.RemoveField(
            model_name='daystat',
            name='act_vol60',
        ),
        migrations.RemoveField(
            model_name='daystat',
            name='act_vol7',
        ),
        migrations.AddField(
            model_name='daystat',
            name='ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='daystat',
            name='fil_prc14',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daystat',
            name='fil_prc30',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daystat',
            name='fil_prc60',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daystat',
            name='fil_prc7',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daystat',
            name='fil_vol14',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daystat',
            name='fil_vol30',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daystat',
            name='fil_vol60',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daystat',
            name='fil_vol7',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daystat',
            name='last_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
