# Generated by Django 4.0.2 on 2022-03-23 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_lowest_price_daystat_current_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_price', models.FloatField()),
                ('fil_prc7', models.FloatField()),
                ('fil_prc14', models.FloatField()),
                ('fil_prc30', models.FloatField()),
                ('fil_prc60', models.FloatField()),
                ('fil_vol7', models.IntegerField()),
                ('fil_vol14', models.IntegerField()),
                ('fil_vol30', models.IntegerField()),
                ('fil_vol60', models.IntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daystats', to='main.day')),
            ],
        ),
        migrations.RenameField(
            model_name='proto',
            old_name='last_stats_at',
            new_name='stats_at',
        ),
        migrations.AddField(
            model_name='proto',
            name='current_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='proto',
            name='qty_on_sale',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='proto',
            name='ratio_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='proto',
            name='runner_price',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='DayStat',
        ),
        migrations.AddField(
            model_name='history',
            name='proto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daystats', to='main.proto'),
        ),
        migrations.AlterUniqueTogether(
            name='history',
            unique_together={('proto', 'day')},
        ),
    ]
