# Generated by Django 4.0.2 on 2022-03-24 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_history_rename_last_stats_at_proto_stats_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='fil_prc14',
            new_name='prc14',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='fil_prc30',
            new_name='prc30',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='fil_prc60',
            new_name='prc60',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='fil_prc7',
            new_name='prc7',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='fil_vol14',
            new_name='vol14',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='fil_vol30',
            new_name='vol30',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='fil_vol60',
            new_name='vol60',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='fil_vol7',
            new_name='vol7',
        ),
        migrations.AlterField(
            model_name='history',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='main.day'),
        ),
        migrations.AlterField(
            model_name='history',
            name='proto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='main.proto'),
        ),
    ]
