# Generated by Django 4.0.2 on 2022-03-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_fil_prc14_history_prc14_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['day']},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['day']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USDC', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='usd',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
